#!/usr/bin/env python3
"""
Generated hook wrapper for bash-validator
Auto-generated by agentic-p build system

This wrapper uses UV for portable Python execution with proper dependency management.
"""

import os
import subprocess
import sys
from pathlib import Path

def main():
    """Main entry point for hook execution"""
    # Get paths
    hook_dir = Path(__file__).parent
    impl_file = hook_dir / "bash-validator.impl.py"
    
    # Navigate to services directory if it exists
    
    services_dir = (hook_dir / "../../../../services/analytics").resolve()
    # No services path, using:
    services_dir = hook_dir
    
    
    # Check if we have uv and pyproject.toml
    use_uv = (services_dir / "pyproject.toml").exists()
    
    if use_uv:
        # Use UV for managed execution
        cmd = [
            "uv", "run",
            "--directory", str(services_dir),
            "python3", str(impl_file)
        ]
    else:
        # Fallback to system Python
        cmd = [sys.executable, str(impl_file)]
    
    # Execute with stdin passthrough
    try:
        result = subprocess.run(
            cmd,
            stdin=sys.stdin,
            stdout=sys.stdout,
            stderr=sys.stderr,
            check=False
        )
        sys.exit(result.returncode)
    except FileNotFoundError as e:
        if "uv" in str(e):
            print(
                "Error: UV not found. Install with: curl -LsSf https://astral.sh/uv/install.sh | sh",
                file=sys.stderr
            )
            sys.exit(127)
        raise

if __name__ == "__main__":
    main()



