#!/usr/bin/env python3
"""
Generated hook wrapper for hooks-collector
Auto-generated by agentic-p build system

This wrapper uses UV for portable Python execution with proper dependency management.
Agent-specific middleware configuration is embedded below.
"""

import os
import subprocess
import sys
import json
import tempfile
from pathlib import Path

# Embedded agent-specific configuration
AGENT_CONFIG = r'''{
  &quot;agent&quot;: &quot;claude-code&quot;,
  &quot;hook_id&quot;: &quot;hooks-collector&quot;,
  &quot;primitive&quot;: {
    &quot;id&quot;: &quot;hooks-collector&quot;,
    &quot;path&quot;: &quot;../../../../primitives/v1/hooks/core/hooks-collector&quot;,
    &quot;impl_file&quot;: &quot;impl.python.py&quot;
  },
  &quot;middleware&quot;: [
    {
      &quot;id&quot;: &quot;analytics-normalizer&quot;,
      &quot;path&quot;: &quot;../../../../services/analytics/middleware/event_normalizer.py&quot;,
      &quot;type&quot;: &quot;analytics&quot;,
      &quot;enabled&quot;: true,
      &quot;events&quot;: [
        &quot;*&quot;
      ],
      &quot;priority&quot;: 10,
      &quot;config&quot;: {
        &quot;debug&quot;: false,
        &quot;provider&quot;: &quot;claude&quot;
      }
    },
    {
      &quot;id&quot;: &quot;analytics-publisher&quot;,
      &quot;path&quot;: &quot;../../../../services/analytics/middleware/event_publisher.py&quot;,
      &quot;type&quot;: &quot;analytics&quot;,
      &quot;enabled&quot;: true,
      &quot;events&quot;: [
        &quot;*&quot;
      ],
      &quot;priority&quot;: 20,
      &quot;config&quot;: {
        &quot;backend&quot;: &quot;file&quot;,
        &quot;output_path&quot;: &quot;./analytics/events.jsonl&quot;
      }
    }
  ],
  &quot;execution&quot;: {
    &quot;strategy&quot;: &quot;parallel&quot;,
    &quot;timeout_sec&quot;: 10,
    &quot;fail_on_error&quot;: false
  },
  &quot;default_decision&quot;: &quot;allow&quot;
}'''

def main():
    """Main entry point for hook execution"""
    # Get paths
    hook_dir = Path(__file__).parent
    impl_file = hook_dir / "impl.python.py"
    
    # Determine project root (where pyproject.toml is)
    # Navigate to services directory
    services_dir = (hook_dir / "../../../../services/analytics").resolve()
    
    # Check if we have uv and pyproject.toml
    use_uv = (services_dir / "pyproject.toml").exists()
    
    # Write config to temp file for impl to read
    config_data = json.loads(AGENT_CONFIG)
    
    # Read hook event from stdin
    input_data = sys.stdin.read()
    
    if input_data:
        try:
            hook_event = json.loads(input_data)
            # Inject config into event data
            hook_event['__agent_config__'] = config_data
            input_json = json.dumps(hook_event)
        except json.JSONDecodeError:
            # If not JSON, pass through as-is
            input_json = input_data
    else:
        # No input, just pass config
        input_json = json.dumps({'__agent_config__': config_data})
    
    if use_uv:
        # Use UV for managed execution
        cmd = [
            "uv", "run",
            "--directory", str(services_dir),
            "python3", str(impl_file)
        ]
    else:
        # Fallback to system Python
        cmd = [sys.executable, str(impl_file)]
    
    # Execute with stdin passthrough
    try:
        process = subprocess.Popen(
            cmd,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        stdout, stderr = process.communicate(input=input_json)
        
        # Pass through stdout/stderr
        if stdout:
            print(stdout, end='')
        if stderr:
            print(stderr, end='', file=sys.stderr)
        
        sys.exit(process.returncode)
    except FileNotFoundError as e:
        if "uv" in str(e):
            print(
                "Error: UV not found. Install with: curl -LsSf https://astral.sh/uv/install.sh | sh",
                file=sys.stderr
            )
            sys.exit(127)
        raise

if __name__ == "__main__":
    main()

